# Generated by Django 2.1.7 on 2019-02-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='origin_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custdata.Customers'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
