# Generated by Django 2.1.7 on 2019-02-27 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custdata', '0004_auto_20190227_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='origin_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
