# Generated by Django 2.1.7 on 2019-02-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custdata', '0005_auto_20190227_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
