# Generated by Django 2.1.7 on 2019-03-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custdata', '0006_auto_20190227_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='cust_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='camp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='refunded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
